/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInput: typeof import('bootstrap-vue-next')['BInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BPopover: typeof import('bootstrap-vue-next')['BPopover']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    DirectoryListing: typeof import('./src/components/DirectoryListing.vue')['default']
    FileSize: typeof import('./src/components/FileSize.vue')['default']
    IBiArrowLeft: typeof import('~icons/bi/arrow-left')['default']
    IBiArrowLeftRight: typeof import('~icons/bi/arrow-left-right')['default']
    IBiArrowRight: typeof import('~icons/bi/arrow-right')['default']
    IBiFileEarmark: typeof import('~icons/bi/file-earmark')['default']
    IBiFileEarmarkPlus: typeof import('~icons/bi/file-earmark-plus')['default']
    IBiFolderFill: typeof import('~icons/bi/folder-fill')['default']
    IBiFolderPlus: typeof import('~icons/bi/folder-plus')['default']
    IBiGearFill: typeof import('~icons/bi/gear-fill')['default']
    IBiHouse: typeof import('~icons/bi/house')['default']
    IBiXLg: typeof import('~icons/bi/x-lg')['default']
    TwoPaneFileDiff: typeof import('./src/components/TwoPaneFileDiff.vue')['default']
    UnifiedFileDiff: typeof import('./src/components/UnifiedFileDiff.vue')['default']
  }
}
