/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInput: typeof import('bootstrap-vue-next')['BInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavForm: typeof import('bootstrap-vue-next')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    IBiArrowLeftRight: typeof import('~icons/bi/arrow-left-right')['default']
    IBiCogs: typeof import('~icons/bi/cogs')['default']
    IBiFileEarmark: typeof import('~icons/bi/file-earmark')['default']
    IBiFileEarmarkPlus: typeof import('~icons/bi/file-earmark-plus')['default']
    IBiFolderFill: typeof import('~icons/bi/folder-fill')['default']
    IBiFolderPlus: typeof import('~icons/bi/folder-plus')['default']
    IBiGearFill: typeof import('~icons/bi/gear-fill')['default']
    IBiGears: typeof import('~icons/bi/gears')['default']
    IBiHouse: typeof import('~icons/bi/house')['default']
    IBiXLg: typeof import('~icons/bi/x-lg')['default']
  }
}
